include:
    - llm-service/compose.yaml
    - llm-service-db/compose.yaml
    - jaeger/compose.yaml
    - rabbitmq/compose.yaml
    - opensearch/compose.yaml
    - doc-processing/compose.yaml

services:
    dozzle:
        container_name: dozzle
        profiles: [logging, full]
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9999:8080"
