services:
  jaeger:
    container_name: businessthing-jaeger
    profiles: [tracing, full, dev]
    image: jaegertracing/all-in-one
    environment:
      - QUERY_BASE_PATH=/tracing
    expose:
      - "16686"
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "5775:5775/udp"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
